name: creddx
description: "CreddX  Crypto Exchange"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^27.1.51
  intl: ^0.19.0
  http: ^1.2.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  image_path: "assets/images/appicon.png"
  android: true
  ios: true
